---

- hosts: servers
  become: true
  tasks:
 
    - name: install apache2 and php packages
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_pachage }}"
        state: latest
        update_cache: yes
