- name: Install http server
  hosts: servers
  become: true
  tasks:

    - name: install apache2 and php package for Ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: "yes"
      when: ansible_distribution == "Ubuntu"
  #   when: ansible_distribution in ["Debian", "Ubuntu"]
  #   when: ansible_os_family == "Debian"

    - name: Change CentOS 8 repository
      shell: |
        sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
        sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.epel.cloud|g' /etc/yum.repos.d/CentOS-Linux-*
        yum makecache
      when: ansible_distribution == "CentOS"

    - name: install httpd and php packages for CentOS
      dnf:
        name: 
         - httpd
         - php
        state: latest
        update_cache: "yes"
      when: ansible_distribution == "CentOS"
