- name: Install http server
  hosts: servers
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: 'yes'
      # when: ansible_distribution in ["Debian", "Ubuntu"]
      when: ansible_os_family == "Debian"

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Change CentOS 8 repository
      shell: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.epel.cloud|g' /etc/yum.repos.d/CentOS-Linux-*
        yum makecache
      when: ansible_distribution == "CentOS"

    - name: Ensure a locale exists
      community.general.locale_gen:
        name: en_US.utf8
        state: present
      when: ansible_os_family == "RedHat"

    - name: update repository index
      dnf:
        update_cache: 'yes'
      when: ansible_os_family == "RedHat"

    - name: install httpd package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

    - name: add php support for apache
      dnf:
        name: php
        state: latest
      # when: ansible_distribution == "CentOS"
      when: ansible_os_family == "RedHat"